openapi: 3.0.0
info:
  title: API сервер для учебного проекта «Что посмотреть».
  description: Список ресурсов и маршрутов сервера «Что посмотреть».
  version: 1.0.0
tags:
  - name: movies
    description: Действия с фильмами
  - name: users
    description: Действия с пользователями
  - name: comments
    description: Действия с комментариями

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Создание нового пользователя
      description: Регистрация нового пользователя

      requestBody:
        description: Информация для создания нового пользователя
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'

      responses:
        "201":
          description: Пользователь зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

        "409":
          description: Пользователь с таким email уже существует.

  /users/login:
    post:
      tags:
        - users
      summary: Вход в закрытую часть приложения
      description: Авторизует пользователя на основе логина и пароля.

      requestBody:
        required: true
        description: Логин и пароль авторизующегося пользователя.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginUser"

      responses:
        "200":
          description:
            Успешно авторизован.
            Возвращается JWT Bearer токен для дальнейшего взаимодействия с API
          content:
            application/json:
              schema:
                type: object

                properties:
                  token:
                    type: string
                    format: jwt

        "401":
          description: Пользователь не существует или в паре логин пароль допущены ошибки.

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю.

      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            format: Bearer jwt

      responses:
        "200":
          description: Получена информация о пользователе.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

        "401":
          description: Пользователь не авторизован. Невалидный токен.

  /movies/create:
    post:
      tags:
        - movies
      summary: Добавление нового фильма
      description: Добавляет новый фильм.

      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            format: Bearer jwt

      requestBody:
        description: Информация для добавления нового фильма.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createMovie'
        required: true

      responses:
        "201":
          description: Фильм добавлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'

        "400":
          description: Некорректный запрос.

        "401":
          description: Пользователь не авторизован.

  /movies/{movieId}:
    get:
      tags:
        - movies
      summary: Получение детальной информации по фильму
      description: Получает детальную информацию по определенному фильму.

      parameters:
        - in: path
          name: movieId
          schema:
            type: string
            format: uuid
          required: true
          description: id фильма.

      responses:
        "200":
          description: Получена детальная информация по фильму.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'

        "404":
          description: Фильма с данным id не существует.

    patch:
      tags:
        - movies
      summary: Редактирование карточки фильма
      description: Редактирует карточку фильма, созданную пользователем.

      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            format: Bearer jwt
        - in: path
          name: movieId
          schema:
            type: string
            format: uuid
          required: true
          description: Movie id to update.

      requestBody:
        description: Полный набор информации и идентификатор редактируемого фильма.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateMovie'
        required: true

      responses:
        "200":
          description: Фильм обновлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'

        "400":
          description: Некорректный запрос.

        "401":
          description: Пользователь не авторизован.

        "403":
          description: У пользователя нет прав на редактирование.

        "404":
          description: Фильма с данным id не существует.

    delete:
      tags:
        - movies
      summary: Удаление карточки фильма.
      description: Удаляет карточку фильма, созданную пользователем.

      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            format: Bearer jwt
        - in: path
          name: movieId
          schema:
            type: string
            format: uuid
          required: true
          description: Movie id to delete.

      requestBody:
        description: Id пользователя, пытающегося удалить фильм.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/deleteMovie"

      responses:
        "204":
          description: Фильм удален.

        "401":
          description: Пользователь не авторизован.

        "403":
          description: Пользователю запрещено удаление данного фильма.

        "404":
          description: Фильма с данным id не существует.

  /movies?limit=60&genre=comedy:
    get:
      tags:
        - movies
      summary: Получение списка фильмов
      description: Возвращает список фильмов (по умолчанию не больше 60).

      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            example: 15
        - in: query
          name: genre
          schema:
            type: string
            enum: [ comedy, crime, documentary, drama, horror, family, romance, scifi, thriller ]
            example: comedy

      responses:
        "200":
          description: Список фильмов получен.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/movieListItem'

        "400":
          description: Некорректный запрос.

  /movies/promo:
    get:
      tags:
        - movies
      summary: Получение промо-фильма
      description: Получение детальной информации по промо фильму.

      responses:
        "200":
          description: Успешно. Детальная информация по промо фильму.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'

  /users/to_watch:
    get:
      tags:
        - users
      summary: Получить список фильмов «К просмотру»
      description: Возвращает список фильмов, добавленных к просмотру

      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            format: Bearer jwt

      responses:
        "200":
          description: Успешно. Фильмы, добавленные к просмотру.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/movieListItem'

        "401":
          description: Пользователь не авторизован.


    post:
      tags:
        - users
      summary: Добавить фильм в список "К просмотру"
      description: Добавляет фильм в список "К просмотру"

      requestBody:
        description: Id фильма, который необходимо добавить из списка "К просмотру"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/addInToWatchList"

      responses:
        "201":
          description: Успешно. Фильм добавлен в список "К просмотру".

        "401":
          description: Пользователь не авторизован.


    delete:
      tags:
        - users
      summary: Удалить фильм из списка "К просмотру"
      description: Удаляет фильм из списка "К просмотру"

      requestBody:
        description: Id фильма, который необходимо убрать из списка "К просмотру"
        content:
          application/json:
            schema:
              type: object

              properties:
                movieId:
                  type: string
                  format: uuid
                  example: 8ddf34525f01410fa3d2e8c2970811bf

              required:
                - movieId

      responses:
        "204":
          description: Успешно. Фильм удален из списка "К просмотру".

        "401":
          description: Пользователь не авторизован.


  /movies/{movieId}/comments:
    get:
      tags:
        - comments
      summary: Получить список комментариев для определённого фильма
      description: Возвращает список комментариев для определенного фильма.

      parameters:
        - in: path
          name: movieId
          schema:
            type: string
            format: uuid
          required: true
          description: Movie id to get comments.

      responses:
        "200":
          description: Успешно. Список комментариев к фильму.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/comment'

        "404":
          description: Фильм с таким id не существует.


  /comments:
    post:
      tags:
        - comments
      summary: Добавить новый комментарий к определённому фильму
      description: Добавляет новый комментарий к определенному фильму

      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            format: Bearer jwt

      requestBody:
        description: Id фильма, к которому добавляют комментарий, и сам комментарий
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/comment'
                - type: object
                  properties:
                    movieId:
                      type: string
                      format: uuid
                      example: 8ddf34525f01410fa3d2e8c2970811bf
                  required:
                    - movieId

      responses:
        "200":
          description: Успешно. Комментарий добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'

        "400":
          description: Не удалось обработать запрос, так как он представлен в неправильном формате или является некорректным

        "401":
          description: Пользователь не авторизован.

        "404":
          description: Фильм с данным id не найден

components:
  schemas:
    createUser:
      type: object

      properties:
        name:
          type: string
          example: Igor

        email:
          type: string
          example: igor@kinopoisk.ru

        password:
          type: string
          example: 1234

    loginUser:
      type: object

      properties:
        login:
          type: string
          example: igor@kinopoisk.ru

        password:
          type: string
          example: 1234

    user:
      type: object

      properties:
        id:
          type: string
          format: uuid
          example: 8ddf34525f01410fa3d2e8c2970811bf

        email:
          type: string
          example: igor@kinopoisk.ru


    createMovie:
      type: object

      properties:
        title:
          type: string
          minLength: 2
          maxLength: 100
          example: Король лев

        description:
          type: string
          minLength: 20
          maxLength: 1024
          example: У величественного Короля-Льва Муфасы рождается наследник по имени Симба. Уже в детстве любознательный малыш становится жертвой интриг своего завистливого дяди Шрама, мечтающего о власти.

        publicationDate:
          type: string
          format: date-time
          example: 2023-01-01T00:00:00.000Z

        genre:
          type: string
          enum: [ comedy, crime, documentary, drama, horror, family, romance, scifi, thriller ]
          example: comedy

        releaseYear:
          type: integer
          example: 1994

        preview:
          type: string
          format: url
          example: https://www.what-to-watch.ru/lion-king-preview

        moviePath:
          type: string
          format: url
          example: https://www.what-to-watch.ru/lion-king

        actors:
          type: array
          items:
            type: string
          minItems: 1
          uniqueItems: true
          example: [ Мэттью Бродерик, Джереми Айронс, Нэйтан Лейн ]

        director:
          type: string
          minLength: 2
          maxLength: 50
          example: Роджер Аллерс

        durationInMinutes:
          type: number
          minimum: 1

        userId:
          type: string
          format: uuid
          example: 8ddf34525f01410fa3d2e8c2970811bf

        poster:
          type: string
          format: uri
          pattern: ([^\s]+(\.jpg)$)
          example: lion_king_poster.jpg

        backgroundImage:
          type: string
          format: uri
          pattern: ([^\s]+(\.jpg)$)
          example: lion_king_background_image.jpg

        backgroundColor:
          type: string
          example: black

      required:
        - title
        - description
        - publicationDate
        - genre
        - releaseYear
        - previewPath
        - moviePath
        - actors
        - director
        - durationInMinutes
        - userId
        - posterPath
        - backgroundImagePath
        - backgroundColor

    movie:
      type: object

      properties:
        title:
          type: string
          minLength: 2
          maxLength: 100
          example: Король лев

        description:
          type: string
          minLength: 20
          maxLength: 1024
          example: У величественного Короля-Льва Муфасы рождается наследник по имени Симба. Уже в детстве любознательный малыш становится жертвой интриг своего завистливого дяди Шрама, мечтающего о власти.

        publicationDate:
          type: string
          format: date-time
          example: 2023-01-01T00:00:00.000Z

        genre:
          type: string
          enum: [ comedy, crime, documentary, drama, horror, family, romance, scifi, thriller ]
          example: comedy

        releaseYear:
          type: integer
          example: 1994

        rating:
          type: integer
          minimum: 0
          maximum: 10
          example: 7

        previewPath:
          type: string
          format: url
          example: https://www.what-to-watch.ru/lion_king_preview

        moviePath:
          type: string
          format: url
          example: https://www.what-to-watch.ru/lion_king

        actors:
          type: array
          items:
            type: string
          minItems: 1
          uniqueItems: true
          example: [ Мэттью Бродерик, Джереми Айронс, Нэйтан Лейн ]

        director:
          type: string
          minLength: 2
          maxLength: 50
          example: Роджер Аллерс

        durationInMinutes:
          type: number
          minimum: 1
          example: 120

        commentsCount:
          type: integer
          minimum: 0
          example: 15

        user:
          $ref: '#/components/schemas/user'

        posterPath:
          type: string
          format: uri
          pattern: ([^\s]+(\.jpg)$)
          example: lion_king_poster.jpg

        backgroundImagePath:
          type: string
          format: uri
          pattern: ([^\s]+(\.jpg)$)
          example: lion_king_background_image.jpg

        backgroundColor:
          type: string
          example: black

      required:
        - title
        - description
        - publicationDate
        - genre
        - releaseYear
        - rating
        - previewPath
        - moviePath
        - actors
        - director
        - durationInMinutes
        - commentsCount
        - user
        - posterPath
        - backgroundImagePath
        - backgroundColor

    updateMovie:
      allOf:
        - $ref: '#/components/schemas/createMovie'
        - type: object
          properties:
            movieId:
              type: string
              format: uuid
              example: 8ddf34525f01410fa3d2e8c2970811bf
          required:
            - movieId

    deleteMovie:
      type: object

      properties:
        userId:
          type: string
          format: uuid

    addInToWatchList:
      type: object

      properties:
        movieId:
          type: string
          format: uuid
          example: 8ddf34525f01410fa3d2e8c2970811bf

      required:
        - movieId

    movieListItem:
      type: object

      properties:
        title:
          type: string
          minLength: 2
          maxLength: 100
          example: Король лев

        publicationDate:
          type: string
          format: date-time
          example: 2023-01-01T00:00:00.000Z

        genre:
          type: string
          enum: [ comedy, crime, documentary, drama, horror, family, romance, scifi, thriller ]
          example: comedy

        previewPath:
          type: string
          format: url
          example: https://www.what-to-watch.ru/lion_king_preview

        user:
          $ref: '#/components/schemas/user'

        posterPath:
          type: string
          format: uri
          pattern: ([^\s]+(\.jpg)$)
          example: lion_king_poster.jpg

        commentsCount:
          type: integer
          minimum: 0
          example: 15

      required:
        - title
        - publicationDate
        - genre
        - preview
        - user
        - poster
        - commentsCount


    comment:
      type: object

      properties:
        text:
          type: string
          minLength: 5
          maxLength: 1024
          example: Мне не понравился этот фильм. очень скучно :(

        rating:
          type: integer
          minimum: 0
          maximum: 10
          example: 2

        publicationDate:
          type: string
          format: date-time
          example: 2023-01-01T00:00:00.000Z

        user:
          $ref: '#/components/schemas/user'

      required:
        - text
        - rating
        - user
